[workspace]
resolver = "2"
members = ["crates/*"]


[workspace.dependencies]
redis = { version = "0.27.5", features = ["tokio-comp"] }
tokio = { version = "1.41.0", features = ["full"] }

[profile.dev]
opt-level = 1

[profile.dev.package.'*']
opt-level = 3
