services:
  db:
    image: postgres:14-alpine
    environment:
      DATABASE_URL: postgresql://postgres:dev_password@db:5432/dev_postgres?sslmode=disable
      POSTGRES_PASSWORD: dev_password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  dbmate:
    image: ghcr.io/amacneil/dbmate:latest
    environment:
      DATABASE_URL: postgresql://postgres:dev_password@db:5432/dev_postgres?sslmode=disable
    volumes:
      - ./crates/db/migrations:/db/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["up"]
    networks:
      - net

  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=dev_password
    command: ["redis-server", "--requirepass", "dev_password"]
    ports:
      - "6379:6379"
    networks:
      - net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /meter
    volumes:
      - ./crates:/meter/crates
      - ./settings:/meter/settings
      - ./static:/meter/static
      - ./logs:/meter/logs
    environment:
      APP_PROFILE: dev
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    command: ["./run-dev.sh"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      dbmate:
        condition: service_completed_successfully
    ports:
      - "8081:80"
    networks:
      - net

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    volumes:
      - ./crates/server/tests/data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  shared_data:
